### ISSUE TITLE
Example of Dataset.export_metadata() passes wrong dsDescription

### ISSUE THREAD

**Issue by pdurbin** [AUSSDA/pyDataverse#27]
I'm using pyDataverse 0.2.1 and trying to get ds.export_metadata working based on the example at https://pydataverse.readthedocs.io/en/v0.2.1/developer.html#pyDataverse.models.Dataset.export_metadata

Here's my code:

```
from pyDataverse.models import Dataset
ds = Dataset()
data = {
    'title': 'pyDataverse study 2019',
    'dsDescription': 'New study about pyDataverse usage in 2019',
    'author': [{'authorName': 'LastAuthor1, FirstAuthor1'}],
    'datasetContact': [{'datasetContactName': 'LastContact1, FirstContact1'}],
    'subject': ['Engineering'],
}
ds.set(data)
ds.export_metadata('export_dataset.json')
```

Here's the error I'm getting:

```
Traceback (most recent call last):
  File "exportds3.py", line 11, in <module>
    ds.export_metadata('export_dataset.json')
  File "/home/pdurbin/envs/dataverse-sample-data/lib/python3.6/site-packages/pyDataverse/models.py", line 1175, in export_metadata
    return write_file_json(filename, self.dict())
  File "/home/pdurbin/envs/dataverse-sample-data/lib/python3.6/site-packages/pyDataverse/models.py", line 945, in dict
    'value': self.__generate_dicts(key, val)
  File "/home/pdurbin/envs/dataverse-sample-data/lib/python3.6/site-packages/pyDataverse/models.py", line 1092, in __generate_dicts
    for k, v in d.items():
AttributeError: 'str' object has no attribute 'items'
```

What am I doing wrong? Thanks.

**Comment by skasberger** [comment]
Will check that.

And: in the function `export_metadata()`, there must be the format passed to `self.dict()` -> `self.dict(format=format)`

**Comment by skasberger** [comment]
The example is wrong, must be:

```
data = {
  'title': 'pyDataverse study 2019',
  'dsDescription': [{'dsDescriptionValue': 'New study about pyDataverse usage in 2019', dsDescriptionDate': '100-02-02'}],
  'author': [{'authorName': 'LastAuthor1, FirstAuthor1'}],
  'datasetContact': [{'datasetContactName': 'LastContact1, FirstContact1'}],
  'subject': ['Engineering'],
}
```

Will fix this in the next release.

**Comment by pdurbin** [comment]
@skasberger thanks! I just came to the same conclusion. Here's a working example:

```
from pyDataverse.models import Dataset
ds = Dataset()
data = {
    'title': 'pyDataverse study 2019',
    'dsDescription':  [{'dsDescriptionValue': 'New study about pyDataverse usage in 2019'}],
    'author': [{'authorName': 'LastAuthor1, FirstAuthor1'}],
    'datasetContact': [{'datasetContactName': 'LastContact1, FirstContact1'}],
    'subject': ['Engineering'],
}
ds.set(data)
ds.export_metadata('export_dataset.json')
```

dsDescription needed to be a list of objects. This is really cool!

**Comment by skasberger** [comment]
the same with `Dataset.set()`.
